### ISSUE TITLE
Error in func (s *Spider) StartBrowser

### ISSUE THREAD

**Issue by EugeneVC** [EDDYCJY/fake-useragent#1]
Hello.

In code func (s *Spider) StartBrowser(..) mistake.

was:
body, err := downloader.Get(url)
				defer body.Close()
				if err != nil {
					return
				}

need:
body, err := downloader.Get(url)
if err != nil {
	return
}
defer body.Close()

**Comment by EDDYCJY** [comment]
@EugeneVC This is an accident, thank you for your feedback.
