### ISSUE TITLE
math/rand: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by theblackturtle** [EDDYCJY/fake-useragent#2]
When run it with large threads, it panic this error.
`ath/rand.(*rngSource).Uint64(...)
        /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc000097500, 0x1)
        /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rng.go:234 +0x89
math/rand.(*Rand).Int63(0xc000082f90, 0x412c70)
        /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rand.go:85 +0x33
math/rand.(*Rand).Int31(0xc000082f90, 0x1)
        /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rand.go:99 +0x2b
math/rand.(*Rand).Int31n(0xc000082f90, 0xbb8, 0xc00052e580)
        /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rand.go:134 +0x4f
math/rand.(*Rand).Intn(0xc000082f90, 0xbb8, 0xfa)
        /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rand.go:172 +0x45`

After google something, I see math/rand is not threads safe. I think we should add mutex for it.

**Comment by eddycjy** [comment]
Hello, I tried to use the method you mentioned, but I can't reproduce it.

```
func main() {
	wg := sync.WaitGroup{}
	for i := 0; i< 10000; i++ {
		wg.Add(1)
		go func() {
			wg.Done()
			random := browser.Random()
			log.Printf("Random: %s", random)
		}()
	}
	wg.Wait()
}
```

Can you describe in detail?

@sieunhando

**Comment by eddycjy** [comment]
@sieunhando hello?

**Comment by eddycjy** [comment]
Unable to reproduce...
